### ISSUE TITLE
Error: Type 'FBoneReference' is not supported by blueprint. 

### ISSUE THREAD

**Issue by grigorovich** [hacoo/ikmod#2]
Doesn't compiles. Fragment from Log :
```
Parsing headers for Test_IK_2Editor
  Running UnrealHeaderTool "/Volumes/Media/Test_IK_2/Intermediate/Build/Mac/Test_IK_2Editor/Development/Test_IK_2Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
/Volumes/Media/Test_IK_2/Plugins/rtik/Source/rtik/Public/IK/IK.h(188) : LogCompile: Error: Type 'FBoneReference' is not supported by blueprint. IKBone.BoneRef
/Volumes/Media/Test_IK_2/Plugins/rtik/Source/rtik/Public/IK/AnimNode_RangeLimitedFabrik.h(64) : LogCompile: Error: Type 'FBoneReference' is not supported by blueprint. AnimNode_RangeLimitedFabrik.EffectorTransformBone
Error: UnrealHeaderTool failed for target 'Test_IK_2Editor' (platform: Mac, module info: /Volumes/Media/Test_IK_2/Intermediate/Build/Mac/Test_IK_2Editor/Development/Test_IK_2Editor.uhtmanifest, exit code: OtherCompilationError (5)).
"/Volumes/Media/Test_IK_2/Test_IK_2.uproject" "/Volumes/Media/Test_IK_2/Intermediate/Build/Mac/Test_IK_2Editor/Development/Test_IK_2Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErr
ors -installed
CompilerResultsLog: Error: /Volumes/Media/Test_IK_2/Plugins/rtik/Source/rtik/Public/IK/IK.h(188)  : LogCompile: Error: Type 'FBoneReference' is not supported by blueprint. IKBone.BoneRef
CompilerResultsLog: Error: /Volumes/Media/Test_IK_2/Plugins/rtik/Source/rtik/Public/IK/AnimNode_RangeLimitedFabrik.h(64)  : LogCompile: Error: Type 'FBoneReference' is not supported by blueprint. AnimNode_RangeLimitedFabrik.EffectorTransformBone
CompilerResultsLog: Error: UnrealHeaderTool failed for target 'Test_IK_2Editor' (platform: Mac, module info: /Volumes/Media/Test_IK_2/Intermediate/Build/Mac/Test_IK_2Editor/Development/Test_IK_2Editor.uhtmanifest, exit code: OtherCompilationError (5)).
```

UE 4.18 Preview 2

**Comment by hacoo** [comment]
I wasn't able to replicate this in 4.16, so this may be a 4.18 issue. I'll try upgrading the project and see what happens.

**Comment by grigorovich** [comment]
Thanks. 
Btw, your code is very nice and ive tested on pc and mac but shows that 2 errors. So if you will fix 'FBoneReference' then i could be check your solver on mac/ios/android platforms with performance profiler.

**Comment by hacoo** [comment]
Looks like Epic made a few changes which made my code incompatible. I went ahead and upgraded the project, it seems to work with 4.17 and 4.18 preview 2 now.

Let me know if this solves the issue. Thanks for the bug report and kind words!

**Comment by grigorovich** [comment]
No probs.
'FBoneReference' error is gone but has new.
I sent log to your mailbox. Description is there as well

**Comment by hacoo** [comment]
Thanks for sending the log!

I wasn't able to replicate this issue in 4.17 - it's compiling with no errors or warnings on a fresh project.  Can you please try the following: 

- Clone the latest version of this repo. You should only need the Plugins/ directory.
- Place the Plugins/ directory in your project base directory
- Delete Intermediate/ and Binaries/ directories
- 'Generate Project Files' and rebuild

It looks like your building on a Mac, so if this doesn't work, it's likely a Mac issue. Unfortunately, I don't own a Mac, so far I've only tested on Windows 10!
